version: '3.8'

services:
  database:
    image: mongo
    container_name: mongo
    ports:
      - 5000:27017
    env_file:
      - ./server/.env
    volumes:
      - database:/data/db

  server:
    build: ./server
    container_name: server
    env_file:
      - ./server/.env
    depends_on:
      - database
    ports:
      - 8000:8000

  client:
    build: ./client
    container_name: client
    ports:
      - 3000:3000
    env_file:
      - ./client/.env
    depends_on:
      - server

volumes:
  database:
